//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Inventory_Control.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mini_Inventory_Control.Langs.Strings - Copy", typeof(Strings___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search collaborator.
        /// </summary>
        internal static string btnBuscarIn {
            get {
                return ResourceManager.GetString("btnBuscarIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from the inventory.
        /// </summary>
        internal static string btnEliminarS {
            get {
                return ResourceManager.GetString("btnEliminarS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data.
        /// </summary>
        internal static string btnGuardarS {
            get {
                return ResourceManager.GetString("btnGuardarS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string btnNuevoC {
            get {
                return ResourceManager.GetString("btnNuevoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search item in inventory.
        /// </summary>
        internal static string btnSearchIn {
            get {
                return ResourceManager.GetString("btnSearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data.
        /// </summary>
        internal static string btnUpdateData {
            get {
                return ResourceManager.GetString("btnUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        internal static string Label10 {
            get {
                return ResourceManager.GetString("Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH FOR AN ITEM.
        /// </summary>
        internal static string label11 {
            get {
                return ResourceManager.GetString("label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPLIER.
        /// </summary>
        internal static string label13 {
            get {
                return ResourceManager.GetString("label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O NUMBER.
        /// </summary>
        internal static string label14 {
            get {
                return ResourceManager.GetString("label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBSERVATIONS.
        /// </summary>
        internal static string label15 {
            get {
                return ResourceManager.GetString("label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT.
        /// </summary>
        internal static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCOMING QUANTITIES.
        /// </summary>
        internal static string Label3 {
            get {
                return ResourceManager.GetString("Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string Label4 {
            get {
                return ResourceManager.GetString("Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVENTORY CONTROL SYSTEM.
        /// </summary>
        internal static string Label5 {
            get {
                return ResourceManager.GetString("Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLLABORATOR.
        /// </summary>
        internal static string Label6 {
            get {
                return ResourceManager.GetString("Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTGOING QUANTITIES.
        /// </summary>
        internal static string Label7 {
            get {
                return ResourceManager.GetString("Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT PRICE.
        /// </summary>
        internal static string Label8 {
            get {
                return ResourceManager.GetString("Label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH A COLLABORATOR.
        /// </summary>
        internal static string Label9 {
            get {
                return ResourceManager.GetString("Label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string optionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("optionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase orders.
        /// </summary>
        internal static string purchaseOrdersToolStripMenuItem {
            get {
                return ResourceManager.GetString("purchaseOrdersToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Control System.
        /// </summary>
        internal static string titleinventory {
            get {
                return ResourceManager.GetString("titleinventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string toolStripMenuItem4 {
            get {
                return ResourceManager.GetString("toolStripMenuItem4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string toolStripMenuItem3
        {
            get
            {
                return ResourceManager.GetString("toolStripMenuItem3", resourceCulture);
            }

        }

        internal static string toolStripMenuItem2
        {
            get
            {
                return ResourceManager.GetString("toolStripMenuItem2", resourceCulture);
            }

        }

        internal static string toolStripMenuItem1
        {
            get
            {
                return ResourceManager.GetString("toolStripMenuItem1", resourceCulture);
            }

        }

        internal static string exitApplicationToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("exitApplicationToolStripMenuItem", resourceCulture);
            }

        }
        internal static string message1
        {
            get
            {
                return ResourceManager.GetString("message1", resourceCulture);
            }

        }

        internal static string message2
        {
            get
            {
                return ResourceManager.GetString("message2", resourceCulture);
            }

        }

        internal static string message3
        {
            get
            {
                return ResourceManager.GetString("message3", resourceCulture);
            }

        }

        internal static string message4
        {
            get
            {
                return ResourceManager.GetString("message4", resourceCulture);
            }

        }

        internal static string message5
        {
            get
            {
                return ResourceManager.GetString("message5", resourceCulture);
            }

        }

        internal static string message6
        {
            get
            {
                return ResourceManager.GetString("message6", resourceCulture);
            }

        }

        internal static string message7
        {
            get
            {
                return ResourceManager.GetString("message7", resourceCulture);
            }

        }

        internal static string LabelPO
        {
            get
            {
                return ResourceManager.GetString("LabelPO", resourceCulture);
            }

        }

        internal static string LabelSU
        {
            get
            {
                return ResourceManager.GetString("LabelSU", resourceCulture);
            }

        }

        internal static string LabelDATE
        {
            get
            {
                return ResourceManager.GetString("LabelDATE", resourceCulture);
            }

        }

        internal static string labelDELIVERY
        {
            get
            {
                return ResourceManager.GetString("labelDELIVERY", resourceCulture);
            }

        }

        internal static string LabelITEM
        {
            get
            {
                return ResourceManager.GetString("LabelITEM", resourceCulture);
            }

        }

        internal static string LabelQTY
        {
            get
            {
                return ResourceManager.GetString("LabelQTY", resourceCulture);
            }

        }

        internal static string labelREQUEST
        {
            get
            {
                return ResourceManager.GetString("labelREQUEST", resourceCulture);
            }

        }

        internal static string labelSEARCHS
        {
            get
            {
                return ResourceManager.GetString("labelSEARCHS", resourceCulture);
            }

        }

        internal static string LabelUNIT
        {
            get
            {
                return ResourceManager.GetString("LabelUNIT", resourceCulture);
            }

        }

        internal static string btnSaveOrder
        {
            get
            {
                return ResourceManager.GetString("btnSaveOrder", resourceCulture);
            }

        }

        internal static string btnDeleteOrder
        {
            get
            {
                return ResourceManager.GetString("btnDeleteOrder", resourceCulture);
            }

        }

        internal static string btnClearOrder
        {
            get
            {
                return ResourceManager.GetString("btnClearOrder", resourceCulture);
            }

        }

        internal static string btnPrintDataOrder
        {
            get
            {
                return ResourceManager.GetString("btnPrintDataOrder", resourceCulture);
            }

        }

        internal static string btnSearchS
        {
            get
            {
                return ResourceManager.GetString("btnSearchS", resourceCulture);
            }

        }

        internal static string titleorder
        {
            get
            {
                return ResourceManager.GetString("titleorder", resourceCulture);
            }

        }

        internal static string lbBar
        {
            get
            {
                return ResourceManager.GetString("lbBar", resourceCulture);
            }

        }

        internal static string leerUnCódigoQRODeBarraToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("leerUnCódigoQRODeBarraToolStripMenuItem", resourceCulture);
            }

        }

        internal static string leerUnCódigoToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("leerUnCódigoToolStripMenuItem", resourceCulture);
            }

        }

        internal static string generateButton1
        {
            get
            {
                return ResourceManager.GetString("generateButton1", resourceCulture);
            }

        }

        internal static string generateBarcodeAndQRCodesToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("generateBarcodeAndQRCodesToolStripMenuItem", resourceCulture);
            }

        }

        internal static string MainWindowBarQr
        {
            get
            {
                return ResourceManager.GetString("MainWindowBarQr", resourceCulture);
            }

        }

        internal static string salirDeLaAplicaciónToolStripMenuItem
        {
            get
            {
                return ResourceManager.GetString("salirDeLaAplicaciónToolStripMenuItem", resourceCulture);
            }

        }

        internal static string OpenCodeForm
        {
            get
            {
                return ResourceManager.GetString("OpenCodeForm", resourceCulture);
            }

        }

        internal static string btnOpenCode
        {
            get
            {
                return ResourceManager.GetString("btnOpenCode", resourceCulture);
            }

        }
    }
}
